version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:some-random-dude
    ports:
      - "443:443"
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/html
    restart: always
    depends_on:
      - wordpress 
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wp-volume:/var/www/html
volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/majrou/data/mariadb
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/majrou/data/wordpress 
  # volumes:
  # db_data:
  networks:
  inception:
